# Generated by Django 5.1.5 on 2025-01-19 09:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0002_rename_auth_status_user_auth_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='auth_status',
            field=models.CharField(choices=[('new', 'new'), ('code_verified', 'code_verified'), ('done', 'done'),
                                            ('photo_done', 'photo_done')], default='new', max_length=31),
        ),
    ]
